author: Jianmin Chen
title: Jianmin Chen
logo: /assets/img/logo.jpeg
description: >-
  This is a blog I'm maintaining in my free time that focuses on programming and whatever I'm obssessed with at the moment.
baseurl: "/blog"
url: "https://jianmin-chen.github.io"
github_username: jianmin-chen
show_downloads: true
show_excerpts: true
theme: jekyll-theme-minimal
